spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/shop_db?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace
